var groupArr=[];var tlMap=new Map();var splittingLinesMap=new Map();var splittingWordsMap=new Map();var splittingCharsMap=new Map();var lines,chars,words;function initAnimation(svg){var id=svg.getAttribute('id');var tl=tlMap.get(id);var isLoadAnimation=svg.getAttribute('data-loaded');if(isLoadAnimation==null||isLoadAnimation=="false"){tl=gsap.timeline();id='_'+Math.random().toString(36).substr(2,9);tlMap.set(id,tl);svg.setAttribute('id',id);var animationAttr=svg.getAttribute('animation');if(animationAttr!=null){var json=JSON.parse(animationAttr);var jsonSripts=json['scriptArr'];loadAnimation(jsonSripts,id,svg);tl.pause();svg.setAttribute('data-loaded',true);}}}
function animate(svg){var id=svg.getAttribute('id');var tl=tlMap.get(id);if(tl!=null){tl.restart();}}
function endAnimation(svg){var id=svg.getAttribute('id');var tl=tlMap.get(id);if(tl!=null){tl.pause();tl.seek(0);}}
function preStartAnimation(svg){var id=svg.getAttribute('id');var tl=tlMap.get(id);var animationAttr=svg.getAttribute('animation');if(animationAttr!=null){var json=JSON.parse(animationAttr);var scriptJsons=json['scriptArr'];if(scriptJsons!=null&&scriptJsons.length!=0){scriptJsons.forEach(scriptJson=>{var countAnimation=0;var isText=scriptJson['isText'];var className=scriptJson['className'];var animations=scriptJson['animations'];var isExit=false;var animationNum=0;var mySplitText,script;if(animations!=null){animations.forEach(animation=>{animationNum+=1;var isRepeat,repeatDuration,isInfinity;script=animation['script'];var startTime=animation['startTime'];var duration=animation['duration'];var options=animation['options'];if(options!=null){Object.keys(options).forEach(key=>{var option=options[key];var optionItems=option['optionItem'];if(optionItems!=null){Object.keys(optionItems).forEach(subKey=>{var item=optionItems[subKey];if(item['selectedOption']){isRepeat=item['isRepeat'];repeatDuration=item['repeatTimes'];isInfinity=item['infinityRepeat'];}});}});}
if(startTime==null){startTime=">";}
if(script!=null){if(animation['isEnterAnimation']==0){countAnimation+=1;}
var cellId=scriptJson['cellId'];if(isText){var items=svg.querySelectorAll('[cell-id=\"'+cellId+'\"]');items.forEach(node=>{if(node.tagName=="foreignObject"){var loopTextChild=function(node){node=node.firstElementChild.firstElementChild.firstElementChild;return getLastWithTextAndOnlyOneElement(node);}
var setTextAnimation=function(textNode){lines=splittingLinesMap.get(cellId);words=splittingWordsMap.get(cellId);chars=splittingCharsMap.get(cellId);if(textNode.getAttribute('isSplit')!='true'){splitTheText(textNode,cellId);mySplitText=new SplitText(textNode,{type:"chars"});chars=mySplitText.chars;splittingCharsMap.set(cellId,chars);}
script=script.replace("this.",'');if(animationNum!=1){if(countAnimation>=1){if(animation['isEnterAnimation']==0){var immediateString=",immediateRender:false";var scriptX=script.lastIndexOf("}");script=script.substring(0,scriptX)+immediateString+script.substring(scriptX,script.length);}}}
if(isExit){isExit=false;tl.add(gsap.set(chars,{x:0,y:0,opacity:1,scale:1,rotation:0}),startTime);tl.add(gsap.set(words,{x:0,y:0,opacity:1,scale:1,rotation:0}),startTime);tl.add(gsap.set(lines,{x:0,y:0,opacity:1,scale:1,rotation:0}),startTime);}
if(animation['isEnterAnimation']==1){isExit=true;}
var a=eval(script);if(isRepeat!=true){a.totalDuration(duration);tl.add(a,startTime);}else{if(!isInfinity){var subTlduration=repeatDuration;var subTl=gsap.timeline();subTl.add(a);subTl.pause();tl.add(subTl.tweenTo(subTlduration),startTime);}else{tl.add(a,startTime);}}}
node=loopTextChild(node);if(node.children!=null&&node>1){var children=node.children;var isBr=false;children.forEach(child=>{if(node.tagName.toLowerCase()=="br"){isBr=true;}else{gsap.set(child,{opacity:1});setTextAnimation(child);}});if(isBr){gsap.set(node,{opacity:1});setTextAnimation(node);}}else{gsap.set(node,{opacity:1});setTextAnimation(node)}}});}}});}});}
if(tl!=null){tl.pause();tl.seek(0);}}}
function loadAnimation(scriptJsons,id,svg){var tl=tlMap.get(id);if(scriptJsons!=null&&scriptJsons.length!=0){scriptJsons.forEach(scriptJson=>{var countAnimation=0;var isGroup=scriptJson['isGroup'];var isText=scriptJson['isText'];var className=scriptJson['className'];var animations=scriptJson['animations'];var isExit=false;var animationNum=0;var mySplitText,script;if(animations!=null){if(isGroup){var group;var isCreatedGroup=false;var groupArr=[];var groupedCellId=scriptJson['groupCellIdArr'];if(groupedCellId!=null){if(groupArr.length!=0){groupArr.forEach(g=>{if(g.classList.contains(className)){isCreatedGroup=true;group=g;}});}
if(isCreatedGroup==false){group=document.createElementNS("http://www.w3.org/2000/svg",'g');group.setAttribute('class',className);svg.appendChild(group);groupedCellId.forEach(id=>{var items=svg.querySelectorAll('[cell-id=\"'+id+'\"]');items.forEach(node=>{if(node.tagName!="mask"&&node.parentNode.tagName!="mask"&&node.tagName!="clipPath"&&node.parentNode.tagName!="clipPath"){group.appendChild(node);}});});groupArr.push(group);}
animations.forEach(animation=>{animationNum+=1;var isRepeat,repeatDuration,isInfinity;script=animation['script'];var startTime=animation['startTime'];var duration=animation['duration'];var options=animations['options'];if(options!=null){Object.keys(options).forEach(key=>{var option=options[key];var optionItems=option['optionItem'];if(optionItems!=null){Object.keys(optionItems).forEach(subKey=>{var item=optionItems[subKey];if(item['selectedOption']){isRepeat=item['isRepeat'];repeatDuration=item['repeatTimes'];isInfinity=item['infinityRepeat'];}});}});}
if(startTime==null){startTime=">";}
if(animation['isEnterAnimation']==0){countAnimation+=1;}
if(script!=null){if(animationNum!=1){if(countAnimation>=1){if(animation['isEnterAnimation']==0){var immediateString=",immediateRender:false";var scriptX=script.lastIndexOf("}");script=script.substring(0,scriptX)+immediateString+script.substring(scriptX,script.length);}}}
script=script.replace("'."+className+"'",'group');if(isExit){isExit=false;tl.add(gsap.set(group,{x:0,y:0,opacity:1,scale:1,rotation:0}),startTime);}
if(animation['isEnterAnimation']==1){isExit=true;}
var a=eval(script);if(duration!=null&&!isRepeat){a.totalDuration(duration);}
if(isRepeat!=true){tl.add(a,startTime);}else{if(!isInfinity){var subTlduration=repeatDuration;var subTl=gsap.timeline();subTl.add(a);subTl.pause();tl.add(subTl.tweenTo(subTlduration),startTime);}else{tl.add(a,startTime);}}}});}}else{animations.forEach(animation=>{animationNum+=1;var isRepeat,repeatDuration,isInfinity;script=animation['script'];var startTime=animation['startTime'];var duration=animation['duration'];var options=animation['options'];if(options!=null){Object.keys(options).forEach(key=>{var option=options[key];var optionItems=option['optionItem'];if(optionItems!=null){Object.keys(optionItems).forEach(subKey=>{var item=optionItems[subKey];if(item['selectedOption']){isRepeat=item['isRepeat'];repeatDuration=item['repeatTimes'];isInfinity=item['infinityRepeat'];}});}});}
if(startTime==null){startTime=">";}
if(script!=null){if(animation['isEnterAnimation']==0){countAnimation+=1;}
var cellId=scriptJson['cellId'];if(isText){var items=svg.querySelectorAll('[cell-id=\"'+cellId+'\"]');items.forEach(node=>{if(node.tagName=="foreignObject"){var loopTextChild=function(node){node=node.firstElementChild.firstElementChild.firstElementChild;return getLastWithTextAndOnlyOneElement(node);}
node=loopTextChild(node);if(node.children!=null&&node>1){var children=node.children;var isBr=false;children.forEach(child=>{if(node.tagName.toLowerCase()=="br"){isBr=true;}else{gsap.set(child,{opacity:0});}});if(isBr){gsap.set(node,{opacity:0});}}else{gsap.set(node,{opacity:0});}}});}else{if(cellId!=null){var items=svg.querySelectorAll('[cell-id=\"'+cellId+'\"]');if(animationNum!=1){if(countAnimation>=1){if(animation['isEnterAnimation']==0){var immediateString=",immediateRender:false";var scriptX=script.lastIndexOf("}");script=script.substring(0,scriptX)+immediateString+script.substring(scriptX,script.length);}}}
items.forEach(node=>{if(node.tagName!="mask"&&node.parentNode.tagName!="mask"&&node.parentNode.tagName!='filter'&&node.tagName!="filter"&&node.tagName!="clipPath"&&node.parentNode.tagName!="clipPath"){script=script.replace("'."+className+"'",'node');if(isExit){isExit=false;tl.add(gsap.set(node,{x:0,y:0,opacity:1,scale:1,rotation:0}),startTime);}
if(animation['isEnterAnimation']==1){isExit=true;}
var a=eval(script);if(repeatDuration==null&&duration!=null){a.totalDuration(duration);}
if(isRepeat!=true){tl.add(a,startTime);}else{if(!isInfinity){var subTlduration=repeatDuration;var subTl=gsap.timeline();subTl.add(a);subTl.pause();tl.add(subTl.tweenTo(subTlduration),startTime);}else{tl.add(a,startTime);}}}});}}
tlMap.set(id,tl);}});}}});}}
function replaceAll(str,find,replace){return str.replace(new RegExp(find,'g'),replace);}
function getIndex(target,type,previousIndex){var theStyle='--'+type+'-index';if(target.getAttribute("style")!=null){var styles=target.getAttribute("style").split(';');var astyle;var previousIndex;for(var i=0;i<styles.length;i++){astyle=styles[i].split(':');if(astyle[0].includes(theStyle)){return(astyle[1]);}}}
return previousIndex;}
function insertAfter(newNode,existingNode){existingNode.parentNode.insertBefore(newNode,existingNode.nextSibling);}
function parentTagNeedToAdd(target,startNode,nodeTagArr){if(target!=startNode.parentNode){nodeTagArr.push(target.tagName.toLowerCase());parentTagNeedToAdd(target.parentNode,startNode,nodeTagArr);}}
function loopGetLines(parent,currentIndex,nodeMap,splittingArr,isFirstLayer){if(nodeMap==null){nodeMap=new Map();}
var childNodeMap;var children=parent.children;var childAppendArr=nodeMap.get(currentIndex);var storedArr=childAppendArr;childAppendArr=[];if(storedArr!=null){nodeMap.delete(currentIndex);}
var index;children=[].slice.call(children);var previousIndex;children.forEach((child,key)=>{if(!child.classList.contains('lineContainer')){if(child.children!=null&&child.children.length>0){nodeMap=loopGetLines(child,currentIndex,nodeMap,splittingArr,false);var arr=nodeMap.get(currentIndex);if(arr!=null&&arr.length>0){var isIncludeStart,isIncludeEnd;var linesArr=splittingArr[currentIndex];arr.forEach(word=>{if(word==linesArr[0]){isIncludeStart=true;}
if(word==linesArr[linesArr.length-1]){isIncludeEnd=true;}});if(isIncludeStart&&isIncludeEnd){childAppendArr=arr;}else if(isIncludeEnd&&!isIncludeStart){var nextLineNodes=[];var targetParent=arr[0].parentNode;var targetChildren=[].slice.call(arr[0].parentNode.children);targetChildren.forEach(targetChild=>{var isNext=true;arr.forEach(a=>{if(a==targetChild){isNext=false;}});if(isNext){nextLineNodes.push(targetChild);if(targetChild.nextElementSibling!=null){nextLineNodes.push(targetChild.nextElementSibling);}}});var nodeTagArr=[];parentTagNeedToAdd(child,childAppendArr[0],nodeTagArr);var childNode;nodeTagArr.forEach((tag,index)=>{var dom=document.createElement(tag);dom.setAttribute('isNextLine',true);if(index==0){nextLineNodes.forEach(nextLineNode=>{dom.appendChild(nextLineNode);});}else{dom.appendChild(childNode);}
childNode=dom;});childAppendArr.push(child);var nextNum=currentIndex+1;nodeMap.set(nextNum,[childNode]);}else{var checkChildren=child.children;var isIncludeOtherLines=false;if(checkChildren!=null){checkChildren=[].slice.call(checkChildren);checkChildren.forEach(c=>{if(c.classList.contains('lineContainer')){isIncludeOtherLines=true;}});}
if(!isIncludeOtherLines){childAppendArr.push(child);}}}}else{var index=getIndex(child,'line',previousIndex);if(currentIndex==index){childAppendArr.push(child);if(child.classList.contains('word')){if(children[key+1]==null||(children[key+1]!=null&&!children[key+1].classList.contains('whitespace'))){var whiteSpace=document.createElement('span');whiteSpace.setAttribute('class','whitespace');whiteSpace.textContent=' ';insertAfter(whiteSpace,child);childAppendArr.push(whiteSpace);}}}
previousIndex=index;}}});if(childAppendArr.length>0){if(storedArr!=null&&storedArr.length>0){var isParentNoNeedToAdd=false;childAppendArr.forEach(c=>{storedArr.forEach(s=>{if(c.parentNode==s){isParentNoNeedToAdd=true;}});if(isParentNoNeedToAdd&&c.classList.contains('word')){isParentNoNeedToAdd=false;}else if(!isParentNoNeedToAdd&&!c.classList.contains('word')){isParentNoNeedToAdd=true;}});if(isParentNoNeedToAdd){storedArr.forEach((storedNode=>{childAppendArr.unshift(storedNode);}));}}
nodeMap.set(currentIndex,childAppendArr);}
if(isFirstLayer){var arr=nodeMap.get(currentIndex);if(arr!=null&&arr.length>0){var div=document.createElement('div');div.style.display='inline-block';div.style.whiteSpace='nowrap';div.setAttribute("class","lineContainer");var parent=arr[0].parentNode;if(parent==null){parent=arr[1].parentNode;}
parent.appendChild(div);if(storedArr!=null){storedArr.forEach((storedNode=>{arr.unshift(storedNode);}));}
arr.forEach((node,index)=>{div.appendChild(node);});nodeMap.set(currentIndex,div);}}
return nodeMap;}
function moveBrOutside(lastNode,value){if(lastNode.tagName.toLowerCase()=='br'){insertAfter(lastNode,value);moveBrOutside(value.lastChild,value);}}
function getSplitingLines(target,cellId){const results=Splitting({target:target,by:'lines'});const length=results[0].lines.length;var nodeMap=new Map();for(var i=0;i<length;i++){nodeMap=loopGetLines(target,i,nodeMap,results[0].lines,true);}
var targetDivs=[];nodeMap.forEach((value,key)=>{var lastNode=value.lastChild;if(lastNode!=null){moveBrOutside(lastNode,value);}
targetDivs.push(value);});lines=targetDivs;words=results[0].words;splittingLinesMap.set(cellId,lines);splittingWordsMap.set(cellId,words);}
function splitTheText(target,cellId){if(typeof(target)=='string'){target=document.querySelector(target);}
getSplitingLines(target,cellId);target.setAttribute('isSplit',true);}
function getLastWithTextAndOnlyOneElement(rs){var children=rs.childNodes;var noTextNode=true;var count=0;if(children!=null){children.forEach(child=>{if(child.nodeType==3){noTextNode=false;}else if(child.nodeType==1){count=count+1;}});}
if(noTextNode&&count==1){rs=getLastWithTextAndOnlyOneElement(rs.firstElementChild);return rs;}else{return rs;}}